### ISSUE TITLE
New Version Build 5990

### ISSUE THREAD

**Issue by clayissimo** [ryosama/mediacoder_unlocker#1]
Hi,

the script doesn't work with V0.8.59, Build 5990. It looks like the script doesn't get the coordinates correctly to enter the answer and the coordinate to click the "continue" button automatically. 
Is it possible to add a function so that these information is user configurable through a config file? I know.. it's just a Perl script, but I can't get Perl properly installed on a Windows 10 machine.

**Comment by ryosama** [comment]
I'll do the test and the modifications soon.

**Comment by ryosama** [comment]
I update the script. It works with MediaCoder V0.8.59, Build 5990 now (and older version).
